"""
The contracts between the model and everything else.

Every exchange with the LLM is one of these shapes. The model is constrained at
decode time to produce valid JSON matching the schema, then validated again on
arrival. It cannot hand us a malformed answer.

Note what is NOT here: there is no schema for pass/fail severity. That is
arithmetic, computed in criteria.py, never generated by the model.
"""

from pydantic import BaseModel, Field


class Measurement(BaseModel):
    parameter: str = Field(description="Name of the measured parameter")
    value: str = Field(description="Measured value including units, exactly as written")


class ReportFacts(BaseModel):
    """Model call 1 output: what the inspection report says."""
    equipment_tag: str
    equipment_description: str
    report_number: str
    inspection_date: str
    measurements: list[Measurement]
    observations: list[str] = Field(description="Notable observations, one per item")


class AdvisoryFinding(BaseModel):
    description: str = Field(description="One or two sentences")
    source_doc: str = Field(description="Document this came from")
    source_page: str = Field(description="Page label, e.g. 'ME-03 p.12'")


class Assessment(BaseModel):
    """Model call 2 output: judgment only, no numeric verdicts."""
    pattern_identified: str = Field(
        description="Named failure pattern the observations match, with its source, "
                    "or 'none identified'")
    advisory_findings: list[AdvisoryFinding] = Field(
        description="Observations worth noting that have no numeric limit")
    recommendation: str = Field(description="What should happen next, two or three sentences")